"""
Help content for the Action Editor.
Each entry maps an action type to rich HTML help text with scenario-based examples.
"""

# Rich HTML help content shown when user clicks ❓ button
# Each entry: meaning + when to use + 3-4 scenario-based examples with explanations
_ACTION_HELP: dict[str, str] = {
    "mouse_click": (
        "<b>🖱 Click — Click chuột trái</b><br><br>"
        "<b>Ý nghĩa:</b> Giả lập 1 lần nhấn chuột trái tại tọa độ (X, Y) cố định, "
        "hoặc tại vị trí ảnh mẫu nếu sử dụng Image Match. Dùng cho mọi thao tác "
        "nhấn nút, chọn item, mở link.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động đăng nhập website</b><br>"
        "Bạn muốn click vào ô 'Username' trên trang login.<br>"
        "→ <b>X=500, Y=300</b> (tọa độ ô input trên màn hình)<br>"
        "→ <b>Duration=0.1s</b> (click nhanh, không cần giữ)<br>"
        "<i>Giải thích:</i> Dùng tọa độ cố định khi vị trí ô input không thay đổi "
        "(cửa sổ trình duyệt luôn maximize).<br><br>"
        "<b>📌 Kịch bản 2: Click nút 'Gửi' trong phần mềm kế toán</b><br>"
        "Nút 'Gửi' có thể ở vị trí khác tùy kích thước cửa sổ.<br>"
        "→ Chọn <b>Image Match</b>: chụp ảnh nút 'Gửi' làm mẫu<br>"
        "→ AutoMacro tự tìm nút trên màn hình → click vào giữa<br>"
        "<i>Giải thích:</i> Image Match an toàn hơn tọa độ khi cửa sổ hay thay đổi kích thước.<br><br>"
        "<b>📌 Kịch bản 3: Click hàng loạt checkbox trong danh sách</b><br>"
        "Bạn cần tick 20 checkbox liên tiếp, mỗi cái cách nhau 30px.<br>"
        "→ <b>X=120, Y=200</b> (checkbox đầu tiên)<br>"
        "→ Kết hợp <b>Loop Block</b>: lặp 20 lần, mỗi lần <b>Y += 30</b><br>"
        "<i>Giải thích:</i> Dùng biến Set Variable để tăng Y mỗi vòng lặp."
    ),
    "mouse_double_click": (
        "<b>🖱 Double Click — Nhấp đúp chuột</b><br><br>"
        "<b>Ý nghĩa:</b> Nhấp đúp chuột trái (2 click nhanh liên tiếp). "
        "Hệ điều hành xử lý double-click khác single-click — dùng để mở file, "
        "chọn từ trong văn bản, kích hoạt item.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động mở file báo cáo Excel hàng ngày</b><br>"
        "Mỗi sáng cần mở file 'BaoCao.xlsx' trên Desktop.<br>"
        "→ <b>X=200, Y=350</b> (vị trí file icon trên Desktop)<br>"
        "<i>Giải thích:</i> Một click chỉ chọn file, double-click mới mở. "
        "Nếu dùng single click → file chỉ được highlight, không mở.<br><br>"
        "<b>📌 Kịch bản 2: Chọn 1 từ trong email để copy</b><br>"
        "Cần chọn từ 'Approved' trong email để kiểm tra trạng thái.<br>"
        "→ Double-click tại vị trí từ → từ được bôi đen<br>"
        "→ Sau đó: Key Combo 'ctrl+c' → Read Clipboard<br>"
        "<i>Giải thích:</i> Double-click trong text editor/browser sẽ tự động chọn cả từ.<br><br>"
        "<b>📌 Kịch bản 3: Kích hoạt ô nhập liệu trong bảng</b><br>"
        "Trong Excel/Google Sheets, single-click chọn cell, double-click mới vào chế độ edit.<br>"
        "→ Double-click cell đích → sau đó Type Text để nhập giá trị"
    ),
    "mouse_right_click": (
        "<b>🖱 Right Click — Click chuột phải</b><br><br>"
        "<b>Ý nghĩa:</b> Mở context menu (menu chuột phải) tại vị trí chỉ định. "
        "Menu sẽ hiện các tùy chọn tùy thuộc vào ứng dụng đang focus.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Xóa file tự động</b><br>"
        "Cần xóa file rác trong thư mục Downloads mỗi tuần.<br>"
        "→ Right-click file → chờ menu hiện (Delay 300ms)<br>"
        "→ Key Press 'D' (phím tắt Delete trong context menu)<br>"
        "<i>Giải thích:</i> Sau right-click cần delay nhỏ để menu hiện ra trước khi nhấn phím.<br><br>"
        "<b>📌 Kịch bản 2: Copy đường dẫn ảnh trên web</b><br>"
        "→ Right-click ảnh → click 'Copy image address'<br>"
        "→ Read Clipboard → Write to File (lưu URL)<br>"
        "<i>Giải thích:</i> Context menu trình duyệt có option copy URL mà Ctrl+C không làm được.<br><br><b>📌 Kịch bản 3: Đổi tên file hàng loạt</b><br>Right-click file → Key Press M (Rename) → Ctrl+A → Type Text tên mới → Enter<br><i>Giải thích:</i> Phím M trong context menu Explorer = Rename. Nhanh hơn click option."
    ),
    "mouse_move": (
        "<b>🖱 Move — Di chuyển chuột</b><br><br>"
        "<b>Ý nghĩa:</b> Di chuyển con trỏ chuột đến vị trí (X, Y) mà không click. "
        "Dùng khi cần hover để kích hoạt tooltip, submenu, hoặc chuẩn bị cho thao tác tiếp.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Mở submenu của thanh menu</b><br>"
        "Trong Excel, hover vào 'Format' → submenu hiện ra.<br>"
        "→ Move đến 'Format' (X=200, Y=30) → Delay 500ms → Click submenu item<br>"
        "<i>Giải thích:</i> Nếu click thẳng vào submenu item mà chưa hover parent → menu chưa hiện.<br><br><b>📌 Kịch bản 2: Hover để hiện tooltip giá trị</b><br>Trong dashboard, hover lên biểu đồ → tooltip hiện số liệu.<br>→ Move đến điểm data (X=450, Y=280) → Delay 1s → Take Screenshot<br><i>Giải thích:</i> Tooltip chỉ hiện khi chuột ở trên phần tử. Delay 1s cho tooltip render.<br><br><b>📌 Kịch bản 3: Chuẩn bị kéo scrollbar</b><br>App không hỗ trợ scroll wheel → cần kéo scrollbar thủ công.<br>→ Move đến scrollbar thumb → Mouse Drag xuống vị trí mới<br><i>Giải thích:</i> Move trước rồi Drag — tách 2 bước cho chính xác."
    ),
    "mouse_drag": (
        "<b>🖱 Drag — Kéo thả chuột</b><br><br>"
        "<b>Ý nghĩa:</b> Nhấn giữ chuột trái tại vị trí hiện tại, "
        "kéo đến tọa độ đích (X, Y), rồi thả. Mô phỏng thao tác drag-and-drop.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Kéo file vào ứng dụng</b><br>"
        "Kéo file ảnh từ Desktop vào cửa sổ Photoshop.<br>"
        "→ Mouse Move đến file icon → Drag đến vùng canvas (X=800, Y=400)<br>"
        "→ Duration=0.5s (kéo chậm để app kịp phản hồi)<br>"
        "<i>Giải thích:</i> Duration quá nhanh (<0.1s) có thể khiến app không nhận drag.<br><br>"
        "<b>📌 Kịch bản 2: Chọn vùng text bằng kéo chuột</b><br>"
        "→ Move đến đầu dòng 1 → Drag đến cuối dòng 3 → Ctrl+C<br>"
        "<i>Giải thích:</i> Khác Ctrl+A (chọn tất cả), drag cho phép chọn chính xác vùng muốn.<br><br><b>📌 Kịch bản 3: Di chuyển widget trong dashboard</b><br>Kéo widget sang vị trí mới trong ứng dụng quản lý.<br>→ Move đến tiêu đề widget → Drag đến (X=200, Y=100), Duration=0.8s<br><i>Giải thích:</i> Web app cần drag chậm để JavaScript kịp xử lý sự kiện dragover."
    ),
    "mouse_scroll": (
        "<b>🖱 Scroll — Cuộn chuột</b><br><br>"
        "<b>Ý nghĩa:</b> Cuộn chuột lên/xuống. Clicks dương = cuộn lên, âm = cuộn xuống.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Cuộn xuống cuối trang web để chụp ảnh</b><br>"
        "→ Loop: Scroll Clicks=-5 → Delay 1s → Take Screenshot → lặp lại<br>"
        "<i>Giải thích:</i> Clicks=-5 cuộn xuống khoảng 5 dòng. Delay cho trang load lazy content.<br><br><b>📌 Kịch bản 2: Zoom bản đồ</b><br>Google Maps, AutoCAD dùng scroll wheel để zoom.<br>→ Move đến vùng cần zoom → Scroll Clicks=3 (zoom in) hoặc -3 (zoom out)<br><i>Giải thích:</i> X, Y xác định trung tâm zoom. Phải Move chuột trước.<br><br><b>📌 Kịch bản 3: Cuộn danh sách dropdown dài</b><br>Dropdown 200 item, cần cuộn xuống item thứ 150.<br>→ Click dropdown → Scroll Clicks=-30 → Click on Image (item cần chọn)<br><i>Giải thích:</i> Clicks=-30 cuộn nhanh ~30 dòng."
    ),
    "key_press": (
        "<b>⌨ Key Press — Nhấn 1 phím</b><br><br>"
        "<b>Ý nghĩa:</b> Nhấn và thả 1 phím đơn: chữ cái, số, hoặc phím đặc biệt "
        "(Enter, Tab, Escape, F1-F12, Home, End, Delete...).<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Xác nhận form sau khi điền xong</b><br>"
        "→ Key = <b>'enter'</b><br>"
        "<i>Giải thích:</i> Nhiều form web chấp nhận Enter để submit, nhanh hơn click nút Submit.<br><br>"
        "<b>📌 Kịch bản 2: Di chuyển giữa các ô trong bảng tính</b><br>"
        "Điền 10 ô liên tiếp: nhập giá trị → Tab → nhập → Tab...<br>"
        "→ Loop: Type Text '{giá_trị}' → Key Press <b>'tab'</b> → lặp<br>"
        "<i>Giải thích:</i> Tab = sang phải, Enter = xuống dưới.<br><br>"
        "<b>📌 Kịch bản 3: Đóng popup phiền toái tự động</b><br>"
        "→ Wait for Image (ảnh popup) → Key Press <b>'esc'</b><br>"
        "<i>Giải thích:</i> Hầu hết dialog/popup đều đóng khi nhấn Escape."
    ),
    "key_combo": (
        "<b>⌨ Key Combo — Tổ hợp phím</b><br><br>"
        "<b>Ý nghĩa:</b> Nhấn đồng thời modifier (Ctrl/Alt/Shift/Win) + phím khác. "
        "Đây là cách gọi shortcut ứng dụng — nhanh hơn click menu.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Copy dữ liệu từ app A sang app B</b><br>"
        "→ Ctrl+A (chọn tất cả) → Ctrl+C → Activate Window 'App B' → Ctrl+V<br>"
        "<i>Giải thích:</i> Key Combo đảm bảo 2 phím nhấn đồng thời. Nếu dùng 2 Key Press riêng → sẽ nhấn tuần tự, không phải combo.<br><br>"
        "<b>📌 Kịch bản 2: Auto-save mỗi 5 phút</b><br>"
        "→ Loop: Delay 300000ms → Key Combo <b>'ctrl+s'</b><br>"
        "<i>Giải thích:</i> Ctrl+S hoạt động trong hầu hết mọi app.<br><br>"
        "<b>📌 Kịch bản 3: Undo 5 bước</b><br>"
        "→ Loop 5: Key Combo <b>'ctrl+z'</b> → Delay 200ms<br>"
        "<i>Giải thích:</i> Delay giữa các Undo để app kịp xử lý mỗi bước."
    ),
    "type_text": (
        "<b>⌨ Type Text — Gõ văn bản</b><br><br>"
        "<b>Ý nghĩa:</b> Gõ chuỗi ký tự vào ô đang focus, từng ký tự một. "
        "Hỗ trợ chữ có dấu tiếng Việt.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động điền 50 email từ file</b><br>"
        "File 'emails.txt', mỗi dòng 1 email.<br>"
        "→ Loop 50: Read File Line → Type Text '{email}' → Tab → lặp<br>"
        "<i>Giải thích:</i> Biến {email} sẽ được thay bằng giá trị đọc từ file.<br><br>"
        "<b>📌 Kịch bản 2: Nhập công thức Excel</b><br>"
        "→ Click cell A1 → Type Text '=SUM(B1:B10)' → Enter<br>"
        "<i>Giải thích:</i> Type Text gõ chính xác từng ký tự, kể cả '=' để Excel nhận diện công thức.<br><br>"
        "<b>📌 Kịch bản 3: Điền form đăng ký</b><br>"
        "→ Click ô Họ tên → Type Text 'Nguyễn Văn A' → Tab → Type Text '0912345678' → Tab → Type Text 'email@gmail.com' → Enter"
    ),
    "hotkey": (
        "<b>⌨ Hotkey — Tổ hợp 3+ phím</b><br><br>"
        "<b>Ý nghĩa:</b> Tương tự Key Combo nhưng hỗ trợ 3 phím trở lên (ví dụ: Ctrl+Shift+S).<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Mở Task Manager khi app bị đơ</b><br>"
        "→ Hotkey <b>'ctrl+shift+esc'</b><br>"
        "<i>Giải thích:</i> Phím tắt mở trực tiếp Task Manager, không cần qua Ctrl+Alt+Del.<br><br>"
        "<b>📌 Kịch bản 2: Save As file với tên mới</b><br>"
        "→ Hotkey <b>'ctrl+shift+s'</b> → Type Text tên mới → Enter<br>"
        "<i>Giải thích:</i> Ctrl+S lưu đè, Ctrl+Shift+S mở 'Save As' để lưu file mới.<br><br><b>📌 Kịch bản 3: Chụp màn hình vùng chọn</b><br>→ Hotkey <b>win+shift+s</b> → đợi Snipping Tool → Drag chọn vùng<br><i>Giải thích:</i> Phím tắt Windows 10/11 mở Snip &amp; Sketch. Macro tự chụp vùng cố định."
    ),
    "wait_for_image": (
        "<b>🖼 Wait for Image — Đợi ảnh xuất hiện</b><br><br>"
        "<b>Ý nghĩa:</b> Tạm dừng macro và liên tục quét màn hình cho đến khi tìm thấy ảnh mẫu "
        "hoặc hết timeout. Đây là cách <b>đồng bộ hóa</b> macro với ứng dụng.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Đợi trang web load xong sau khi đăng nhập</b><br>"
        "Sau khi nhấn 'Login', trang cần 2-10s load tùy mạng.<br>"
        "→ Ảnh mẫu = <b>logo trang dashboard</b>, Timeout = <b>30s</b><br>"
        "<i>Giải thích:</i> Nếu dùng Delay cố định (5s), mạng chậm → macro click trang chưa load. "
        "Wait for Image tự adjust: mạng nhanh → chuyển ngay, mạng chậm → đợi thêm.<br><br>"
        "<b>📌 Kịch bản 2: Đợi file download xong</b><br>"
        "→ Ảnh mẫu = <b>'Download complete'</b>, Timeout = <b>120s</b><br>"
        "<i>Giải thích:</i> Dùng Timeout lớn cho file lớn. Nếu quá timeout → on_error xử lý.<br><br><b>📌 Kịch bản 3: Đợi máy in hoàn tất</b><br>Gửi lệnh in → đợi thông báo hoàn tất hiện trên taskbar.<br>→ Ảnh mẫu = <b>icon máy in OK</b>, Timeout = <b>180s</b><br><i>Giải thích:</i> Timeout 3 phút cho tài liệu dài. Macro tiếp ngay khi in xong."
    ),
    "click_on_image": (
        "<b>🖼 Click on Image — Tìm ảnh rồi click</b><br><br>"
        "<b>Ý nghĩa:</b> Quét toàn bộ màn hình tìm ảnh mẫu, rồi click vào giữa vùng tìm thấy. "
        "Giải quyết vấn đề nút ở vị trí thay đổi.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Auto-click nút 'OK' trong mọi popup</b><br>"
        "Nút OK nằm ở vị trí khác nhau mỗi lần popup hiện.<br>"
        "→ Ảnh mẫu = <b>ảnh nút OK</b>, Confidence = <b>0.8</b><br>"
        "<i>Giải thích:</i> Confidence 0.8 = chấp nhận khớp 80%. "
        "Thấp quá (0.5) → click nhầm. Cao quá (0.99) → không tìm thấy khi font hơi khác.<br><br>"
        "<b>📌 Kịch bản 2: Click icon trong System Tray</b><br>"
        "Icon system tray rất nhỏ (16×16px), tọa độ thay đổi tùy số app chạy.<br>"
        "→ Ảnh mẫu = ảnh icon app (chụp từ tray)<br>"
        "<i>Giải thích:</i> Tọa độ cố định sẽ sai khi có app khác mở/đóng.<br><br><b>📌 Kịch bản 3: Chọn sản phẩm theo ảnh</b><br>Click vào ảnh sản phẩm trong danh sách web shop.<br>→ Ảnh mẫu = thumbnail chụp sẵn, Confidence = <b>0.85</b><br><i>Giải thích:</i> Ảnh có thể resize nhẹ → 0.85 cho phép sai lệch nhỏ."
    ),
    "image_exists": (
        "<b>🖼 Image Exists — Kiểm tra ảnh tồn tại</b><br><br>"
        "<b>Ý nghĩa:</b> Check 1 lần duy nhất xem ảnh mẫu có trên màn hình không (True/False). "
        "Khác Wait for Image: không đợi, chỉ check ngay lúc đó.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Kiểm tra đã login chưa trước khi làm việc</b><br>"
        "→ Image Exists: ảnh = <b>avatar user</b><br>"
        "→ Nếu có → tiếp tục. Nếu không → run macro 'login.json'<br>"
        "<i>Giải thích:</i> Kết hợp với If Image Found để rẽ nhánh tự động.<br><br><b>📌 Kịch bản 2: Kiểm tra có popup lỗi không</b><br>Sau submit form, check popup Error.<br>→ Image Exists: ảnh <b>icon lỗi đỏ</b><br>→ Nếu có → Take Screenshot → dừng. Nếu không → tiếp tục<br><i>Giải thích:</i> Check nhanh 1 lần, không đợi như Wait for Image.<br><br><b>📌 Kịch bản 3: Kiểm tra app đã mở chưa</b><br>→ Image Exists: ảnh <b>title bar app</b><br>→ Không có → mở app → Delay 3s → check lại<br><i>Giải thích:</i> Tránh lỗi khi macro chạy mà app đích chưa sẵn sàng."
    ),
    "take_screenshot": (
        "<b>🖼 Take Screenshot — Chụp màn hình</b><br><br>"
        "<b>Ý nghĩa:</b> Chụp toàn bộ màn hình lưu thành file .png. File đặt tên theo timestamp.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Chụp xác nhận sau mỗi đơn hàng</b><br>"
        "Macro xử lý 50 đơn hàng, mỗi đơn cần chụp ảnh xác nhận.<br>"
        "→ Loop 50: xử lý đơn → <b>Take Screenshot</b> → lặp<br>"
        "<i>Giải thích:</i> File ảnh tự đặt tên theo timestamp → không bao giờ ghi đè.<br><br><b>📌 Kịch bản 2: Debug macro bị lỗi</b><br>Macro sai ở bước 15 → chèn Take Screenshot trước bước 15 để xem UI.<br><i>Giải thích:</i> Ảnh giúp thấy chính xác trạng thái màn hình lúc lỗi.<br><br><b>📌 Kịch bản 3: Lưu bằng chứng giao dịch online</b><br>→ Sau chuyển tiền xong → Take Screenshot<br><i>Giải thích:</i> Timestamp trong tên file = bằng chứng thời điểm giao dịch."
    ),
    "check_pixel_color": (
        "<b>🎨 Check Pixel Color — Kiểm tra màu pixel</b><br><br>"
        "<b>Ý nghĩa:</b> Lấy màu RGB tại tọa độ (X, Y) và so sánh. "
        "<b>Nhanh gấp 100x</b> so với Image Match — chỉ kiểm tra 1 điểm.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Kiểm tra nút Submit có active không</b><br>"
        "Nút active = xanh #4CAF50, disabled = xám #999.<br>"
        "→ Check pixel giữa nút (X=400, Y=500)<br>"
        "→ Xanh → click. Xám → đợi thêm<br>"
        "<i>Giải thích:</i> Nhanh hơn nhiều so với Image Match vì chỉ 1 pixel.<br><br><b>📌 Kịch bản 2: Giám sát server trong dashboard</b><br>Icon server: xanh = online, đỏ = offline.<br>→ Check pixel giữa icon → Xanh → OK. Đỏ → alert email<br><i>Giải thích:</i> Polling mỗi 60s, cực nhẹ vì chỉ check 1 pixel.<br><br><b>📌 Kịch bản 3: Phát hiện trang web load xong</b><br>Loading: nền trắng. Load xong: nền app tối.<br>→ Check pixel vùng content → đổi màu = đã load<br><i>Giải thích:</i> Thay Wait for Image khi không có ảnh mẫu rõ ràng."
    ),
    "wait_for_color": (
        "<b>🎨 Wait for Color — Đợi pixel đổi màu</b><br><br>"
        "<b>Ý nghĩa:</b> Liên tục check pixel tại (X, Y) cho đến khi đúng màu hoặc hết timeout.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Đợi progress bar đầy rồi tiếp tục</b><br>"
        "Thanh loading khi full = xanh #00FF00.<br>"
        "→ Tọa độ = cuối thanh (X=700, Y=580), Màu = #00FF00, Timeout = 60s<br>"
        "<i>Giải thích:</i> Check pixel cuối thanh: khi chuyển xanh → thanh đã full.<br><br><b>📌 Kịch bản 2: Đợi video render xong</b><br>Nút Export xám → render xong chuyển xanh #4CAF50.<br>→ Tọa độ = giữa nút, Màu = #4CAF50, Timeout = 600s<br><i>Giải thích:</i> Timeout 10 phút cho video dài. Xanh → click Export.<br><br><b>📌 Kịch bản 3: Đợi máy CNC sẵn sàng</b><br>Đèn: đỏ = đang chạy, xanh = sẵn sàng.<br>→ Wait for Color: pixel đèn, Màu = xanh, Timeout = 120s<br><i>Giải thích:</i> Đảm bảo máy dừng trước khi gửi lệnh mới."
    ),
    "delay": (
        "<b>⏱ Delay — Tạm dừng</b><br><br>"
        "<b>Ý nghĩa:</b> Dừng macro trong thời gian chỉ định (millisecond). 1000ms = 1 giây.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Đợi animation menu rồi mới click</b><br>"
        "Menu dropdown có animation 300ms.<br>"
        "→ Click menu → <b>Delay 500ms</b> → Click item<br>"
        "<i>Giải thích:</i> 500ms > 300ms animation → menu chắc chắn đã hiện hết.<br><br>"
        "<b>📌 Kịch bản 2: Chống rate-limit khi gửi email hàng loạt</b><br>"
        "→ Loop: soạn email → gửi → <b>Delay 3000ms</b> → lặp<br>"
        "<i>Giải thích:</i> 3s giữa các email ≈ 20 email/phút, an toàn cho hầu hết hệ thống.<br><br>"
        "<b>💡 Tip:</b> Nếu không biết trước thời gian cần chờ, dùng <b>Wait for Image</b> thay vì Delay cố định — linh hoạt hơn."
    ),
    "loop_block": (
        "<b>🔁 Loop Block — Vòng lặp</b><br><br>"
        "<b>Ý nghĩa:</b> Lặp lại nhóm action N lần hoặc vô hạn. "
        "Nền tảng cho mọi xử lý hàng loạt (batch).<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Gửi 100 email từ danh sách</b><br>"
        "→ Loop 100: Read File Line → Click 'To:' → Type Text '{email}' → soạn → Gửi → Delay 3s<br>"
        "<i>Giải thích:</i> Mỗi vòng Read File Line tự động đọc dòng tiếp theo.<br><br><b>📌 Kịch bản 2: Monitor server 24/7 (loop vô hạn)</b><br>→ Loop ∞: Check Pixel → If đỏ → alert → Delay 300000ms<br><i>Giải thích:</i> Count=0 = vô hạn. Delay 5 phút tránh spam.<br><br><b>📌 Kịch bản 3: In 30 hóa đơn liên tiếp</b><br>→ Loop 30: điền thông tin → Ctrl+P → Enter → Delay 5s<br><i>Giải thích:</i> Delay 5s đợi in xong trước hóa đơn tiếp."
    ),
    "if_image_found": (
        "<b>🔀 If Image Found — Rẽ nhánh theo ảnh</b><br><br>"
        "<b>Ý nghĩa:</b> Kiểm tra ảnh có trên màn hình → thực hiện hành động khác nhau. "
        "Đây là <b>logic điều kiện</b> quan trọng nhất.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động xử lý popup bất ngờ</b><br>"
        "Macro chạy, popup 'Are you sure?' bất ngờ hiện.<br>"
        "→ If Image Found: ảnh nút 'Yes'<br>"
        "→ Có → Click on Image 'Yes'. Không → bỏ qua, tiếp tục<br>"
        "<i>Giải thích:</i> Đặt trong loop → tự xử lý popup bất cứ lúc nào hiện ra.<br><br>"
        "<b>📌 Kịch bản 2: Kiểm tra login thành công</b><br>"
        "→ If Image Found: ảnh 'Dashboard'<br>"
        "→ Có → tiếp. Không → Take Screenshot lỗi → dừng<br><br><b>📌 Kịch bản 3: Skip quảng cáo YouTube</b><br>→ If Image Found: ảnh nút Skip Ad<br>→ Có → Click. Không → đợi 5s rồi check lại<br><i>Giải thích:</i> Nút Skip chỉ hiện sau vài giây. Đặt trong loop để skip mọi ad."
    ),
    "if_pixel_color": (
        "<b>🔀 If Pixel Color — Rẽ nhánh theo màu</b><br><br>"
        "<b>Ý nghĩa:</b> Kiểm tra màu pixel → rẽ nhánh. Nhanh gấp 100x so với If Image.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Kiểm tra HP trong game</b><br>"
        "HP bar: đỏ = full, đen = hết.<br>"
        "→ Check pixel giữa HP bar<br>"
        "→ Đỏ → tiếp tục attack. Đen → dùng potion heal<br>"
        "<i>Giải thích:</i> Check pixel mỗi 100ms — rất nhanh, phù hợp game loop.<br><br><b>📌 Kịch bản 2: Auto-farm game</b><br>Minimap: đỏ = có quái, xanh = an toàn.<br>→ Đỏ → attack. Xanh → tiếp tục farm<br><i>Giải thích:</i> Minimap dùng màu cố định → pixel check đáng tin.<br><br><b>📌 Kịch bản 3: Kiểm tra email mới Outlook</b><br>Icon thông báo: xanh = email mới, xám = không.<br>→ Xanh → Click. Xám → Delay 60s rồi check lại<br><i>Giải thích:</i> Polling nhẹ mỗi phút thay vì Image Match nặng."
    ),
    "if_variable": (
        "<b>🔀 If Variable — Rẽ nhánh theo biến</b><br><br>"
        "<b>Ý nghĩa:</b> So sánh giá trị biến (==, !=, >, <, contains).<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Dừng sau N lần lặp</b><br>"
        "→ Set Variable 'count' = '{count} + 1'<br>"
        "→ If Variable: count > 50 → Dừng macro<br>"
        "<i>Giải thích:</i> Kiểm soát chính xác hơn Loop Block thông thường.<br><br>"
        "<b>📌 Kịch bản 2: Kiểm tra kết quả OCR</b><br>"
        "→ Capture Text → biến 'result'<br>"
        "→ If Variable: result contains 'thành công' → tiếp. Không → Log lỗi<br>"
        "<i>Giải thích:</i> Dùng 'contains' thay '==' vì OCR có thể trả thêm khoảng trắng thừa.<br><br><b>📌 Kịch bản 3: Xử lý theo loại file</b><br>→ Split tên file lấy ext → If ext == pdf → mở Reader<br>→ If ext == xlsx → mở Excel<br><i>Giải thích:</i> Nhiều If Variable liên tiếp = switch-case đơn giản."
    ),
    "set_variable": (
        "<b>📊 Set Variable — Gán giá trị biến</b><br><br>"
        "<b>Ý nghĩa:</b> Tạo hoặc cập nhật biến. Hỗ trợ số, chuỗi, và tham chiếu {tên_biến}.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tạo bộ đếm</b><br>"
        "→ Set Variable: Name = 'counter', Value = '0' (trước loop)<br>"
        "→ Trong loop: Value = '{counter} + 1'<br>"
        "<i>Giải thích:</i> {counter} thay bằng giá trị hiện tại, +1 → tự tăng mỗi vòng.<br><br>"
        "<b>📌 Kịch bản 2: Tên file động</b><br>"
        "→ Value = 'report_{counter}.pdf'<br>"
        "<i>Giải thích:</i> Mỗi vòng tạo tên file khác: report_1.pdf, report_2.pdf...<br><br><b>📌 Kịch bản 3: Lưu timestamp đặt tên file</b><br>→ Set Variable: Name = ts, Value = {timestamp}<br>→ Write to File: backup_{ts}.txt<br><i>Giải thích:</i> {timestamp} là biến hệ thống, trả về thời gian hiện tại."
    ),
    "split_string": (
        "<b>📊 Split String — Tách chuỗi</b><br><br>"
        "<b>Ý nghĩa:</b> Tách chuỗi theo ký tự phân cách, lấy phần tử theo index (0 = đầu, -1 = cuối).<br>"
        "<hr>"
        "<b>📌 Kịch bản: Xử lý file CSV</b><br>"
        "Dòng CSV: 'Nguyễn Văn A,email@gmail.com,0912345678'<br>"
        "→ Split: Separator = ',' → Index 0 = tên, Index 1 = email, Index 2 = SĐT<br>"
        "<i>Giải thích:</i> Sau Split, mỗi phần tử lưu vào biến riêng → Type Text từng ô.<br><br><b>📌 Kịch bản 2: Tách domain từ email</b><br>Email: user@company.com<br>→ Split: Separator = @ → Index 1 = company.com<br><i>Giải thích:</i> Kiểm tra domain: nếu nội bộ → xử lý, ngược lại → bỏ qua.<br><br><b>📌 Kịch bản 3: Lấy tên file từ đường dẫn</b><br>Path: C:/Users/Admin/report.pdf<br>→ Split: Separator = / → Index -1 = report.pdf (phần tử cuối)<br><i>Giải thích:</i> Index -1 luôn lấy cuối cùng, bất kể path dài bao nhiêu."
    ),
    "comment": (
        "<b>📝 Comment — Ghi chú</b><br><br>"
        "<b>Ý nghĩa:</b> Nhãn ghi chú không thực thi. Engine bỏ qua hoàn toàn khi chạy.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Đánh dấu phần trong macro dài</b><br>"
        "Macro 50 action khó theo dõi → thêm Comment phân section:<br>"
        "→ <b>'=== PHẦN 1: ĐĂNG NHẬP ==='</b><br>"
        "→ <b>'⚠ LƯU Ý: Server chậm, cần đợi 5s'</b><br>"
        "<i>Giải thích:</i> Giúp macro 'self-documenting' — đọc lại sau 1 tháng vẫn hiểu.<br><br><b>📌 Kịch bản 2: Ghi chú TODO</b><br>→ TODO: Thêm xử lý lỗi timeout ở bước này<br><i>Giải thích:</i> Đánh dấu vị trí cần cải thiện — giống comment trong code.<br><br><b>📌 Kịch bản 3: Đánh dấu vùng disable khi debug</b><br>→ Thêm Comment === DISABLED === phía trên nhóm action cần tắt<br><i>Giải thích:</i> Giúp nhận biết vùng nào đang bị disable khi nhìn danh sách."
    ),
    "activate_window": (
        "<b>🖥 Activate Window — Chuyển cửa sổ</b><br><br>"
        "<b>Ý nghĩa:</b> Tìm cửa sổ theo tiêu đề (hoặc 1 phần) và đưa lên foreground.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Macro thao tác giữa Chrome và Excel</b><br>"
        "→ Activate Window <b>'Chrome'</b> → copy dữ liệu<br>"
        "→ Activate Window <b>'BaoCao.xlsx'</b> → paste vào Excel<br>"
        "<i>Giải thích:</i> Chỉ cần 1 phần tiêu đề: 'Chrome' sẽ match 'Báo cáo - Google Chrome'.<br><br><b>📌 Kịch bản 2: Dùng Notepad làm clipboard trung gian</b><br>→ Activate Window Notepad → Ctrl+V → Ctrl+S<br><i>Giải thích:</i> Lưu dữ liệu tạm khi cần paste giữa các bước.<br><br><b>📌 Kịch bản 3: Quay lại app chính sau popup</b><br>→ Xử lý popup xong → Activate Window app chính<br><i>Giải thích:</i> Popup đổi focus → Activate Window đưa đúng app lên lại."
    ),
    "log_to_file": (
        "<b>📝 Log to File — Ghi log</b><br><br>"
        "<b>Ý nghĩa:</b> Nối (append) 1 dòng text vào file log. Hỗ trợ biến {counter}, {timestamp}.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Ghi nhật ký chạy macro</b><br>"
        "→ Mỗi vòng: Log to File <b>'Vòng {counter}: xử lý {email} — OK'</b><br>"
        "<i>Giải thích:</i> Sau khi chạy xong, mở file log → biết rõ đã xử lý bao nhiêu item.<br><br><b>📌 Kịch bản 2: Log lỗi kèm timestamp</b><br>→ Log to File: [{timestamp}] ERROR: Không tìm thấy ảnh nút OK<br><i>Giải thích:</i> Timestamp giúp biết chính xác thời điểm lỗi → dễ debug.<br><br><b>📌 Kịch bản 3: Báo cáo tổng hợp sau macro</b><br>→ Log to File: Tổng: {counter}, Thành công: {success}, Lỗi: {error}<br><i>Giải thích:</i> Đặt sau loop → tổng kết. Dùng nhiều biến trong 1 dòng."
    ),
    "read_clipboard": (
        "<b>📋 Read Clipboard — Đọc clipboard</b><br><br>"
        "<b>Ý nghĩa:</b> Lấy text trong clipboard (sau Ctrl+C) vào biến để xử lý tiếp.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Lấy URL từ thanh địa chỉ trình duyệt</b><br>"
        "→ Click thanh địa chỉ → Ctrl+A → Ctrl+C<br>"
        "→ <b>Read Clipboard</b> → biến 'url' → Write to File<br>"
        "<i>Giải thích:</i> Ctrl+C copy vào clipboard, Read Clipboard lấy ra để macro sử dụng.<br><br><b>📌 Kịch bản 2: So sánh giá sản phẩm</b><br>→ Double-click giá shop 1 → Ctrl+C → Read Clipboard → biến price_1<br>→ Chuyển tab → lặp lại → biến price_2 → If price_1 &lt; price_2 → chọn shop 1<br><i>Giải thích:</i> Read Clipboard lưu vào biến → so sánh tự động.<br><br><b>📌 Kịch bản 3: Lấy dữ liệu từ app legacy</b><br>→ Ctrl+C trong app cũ → Read Clipboard → Write to File<br><i>Giải thích:</i> Clipboard là cầu nối duy nhất giữa app cũ và macro."
    ),
    "read_file_line": (
        "<b>📄 Read File Line — Đọc dòng từ file</b><br><br>"
        "<b>Ý nghĩa:</b> Đọc dòng thứ N từ file text vào biến. "
        "Trong loop, tự động đọc dòng tiếp theo mỗi vòng.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Nhập 100 tài khoản từ file</b><br>"
        "File 'accounts.txt' mỗi dòng: username,password<br>"
        "→ Loop 100: Read File Line → Split ',' → Type Text user → Tab → Secure Type pass → Enter<br>"
        "<i>Giải thích:</i> Kết hợp Read File Line + Split String = đọc CSV cơ bản.<br><br><b>📌 Kịch bản 2: Mở 50 URL từ file</b><br>→ Loop 50: Read File Line → Ctrl+L → Type Text {url} → Enter → Delay 3s<br><i>Giải thích:</i> Ctrl+L focus thanh địa chỉ mọi trình duyệt.<br><br><b>📌 Kịch bản 3: Chạy danh sách lệnh SQL</b><br>→ Read File Line → paste vào editor → F5 (Execute) → Delay 2s<br><i>Giải thích:</i> Mỗi dòng = 1 câu SQL. Macro chạy lần lượt."
    ),
    "write_to_file": (
        "<b>📄 Write to File — Ghi vào file</b><br><br>"
        "<b>Ý nghĩa:</b> Ghi text vào file (tạo mới hoặc nối thêm). Hỗ trợ biến.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Xuất kết quả ra CSV</b><br>"
        "→ File = 'result.csv', Text = '{name},{email},{phone}'<br>"
        "→ Mode = Append (nối thêm, không ghi đè)<br>"
        "<i>Giải thích:</i> Chế độ Append thêm dòng mới mỗi lần → tạo file CSV nhiều dòng.<br><br><b>📌 Kịch bản 2: Tạo file cấu hình tự động</b><br>→ File = config.ini, Mode = Overwrite<br>→ Nội dung: Server={server}, Port={port}<br><i>Giải thích:</i> Mode Overwrite tạo file mới. Dùng cho config cần cập nhật.<br><br><b>📌 Kịch bản 3: Ghi danh sách lỗi</b><br>→ Write to File: errors.txt, Append, Text = Item {counter}: lỗi bước xác nhận<br><i>Giải thích:</i> Sau macro xong, mở errors.txt → biết item nào lỗi."
    ),
    "secure_type_text": (
        "<b>🔒 Secure Type Text — Gõ bảo mật</b><br><br>"
        "<b>Ý nghĩa:</b> Gõ text nhưng <b>không hiển thị</b> trong log/preview. Chỉ hiện '****'.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Tự động đăng nhập hệ thống</b><br>"
        "→ Click ô Password → <b>Secure Type Text</b> 'P@ssw0rd!'<br>"
        "→ Trong log chỉ hiện: 'type_text: ****'<br>"
        "<i>Giải thích:</i> Type Text thường → password hiện rõ trong log → rủi ro bảo mật.<br><br><b>📌 Kịch bản 2: Nhập API key</b><br>→ Click ô API Key → Secure Type Text sk-abc123xyz789<br><i>Giải thích:</i> API key nhạy cảm như password — lộ = mất tài khoản.<br><br><b>📌 Kịch bản 3: Nhập mã OTP/PIN</b><br>→ Read Clipboard (OTP) → Secure Type Text {otp}<br><i>Giải thích:</i> OTP dùng 1 lần nhưng vẫn nên ẩn để tránh replay attack."
    ),
    "run_macro": (
        "<b>📦 Run Sub-Macro — Chạy macro con</b><br><br>"
        "<b>Ý nghĩa:</b> Chạy file macro khác (.json) như subroutine. Xong → quay lại macro chính.<br>"
        "<hr>"
        "<b>📌 Kịch bản: Tái sử dụng flow đăng nhập</b><br>"
        "Nhiều macro đều cần login → tạo 'login.json' riêng.<br>"
        "→ Macro A: <b>Run 'login.json'</b> → xử lý A<br>"
        "→ Macro B: <b>Run 'login.json'</b> → xử lý B<br>"
        "<i>Giải thích:</i> Thay đổi flow login → chỉ sửa 1 file thay vì sửa tất cả macro.<br><br><b>📌 Kịch bản 2: Chia macro dài thành modules</b><br>Macro 200 action → chia 3 file nhỏ:<br>→ Run 01_login → Run 02_nhap_lieu → Run 03_xuat_bao_cao<br><i>Giải thích:</i> Giống chia code thành hàm — dễ bảo trì, test từng phần.<br><br><b>📌 Kịch bản 3: Chạy macro tùy điều kiện</b><br>→ If Variable: type == invoice → Run xu_ly_hoa_don.json<br>→ If Variable: type == receipt → Run xu_ly_phieu_thu.json<br><i>Giải thích:</i> Kết hợp If Variable + Run Macro = routing logic linh hoạt."
    ),
    "capture_text": (
        "<b>🔎 Capture Text (OCR) — Nhận dạng chữ</b><br><br>"
        "<b>Ý nghĩa:</b> Chụp vùng màn hình, nhận dạng text bằng Tesseract OCR, lưu vào biến. "
        "Cho phép macro 'đọc' text trên UI.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Đọc số dư tài khoản ngân hàng</b><br>"
        "→ Vùng chụp = khu vực hiển thị số dư (X1=300, Y1=200, X2=500, Y2=230)<br>"
        "→ Biến = 'balance' → Log to File 'Số dư: {balance}'<br>"
        "<i>Giải thích:</i> OCR chuyển ảnh text thành chuỗi ký tự macro có thể xử lý.<br><br>"
        "<b>📌 Kịch bản 2: Đọc mã đơn hàng từ popup</b><br>"
        "→ Capture Text vùng mã đơn → biến 'order_id' → Write to File<br>"
        "<i>Giải thích:</i> Dùng khi UI không cho Ctrl+C (text trong ảnh, canvas, PDF viewer).<br><br><b>📌 Kịch bản 3: Đọc mã vận đơn từ nhãn in</b><br>→ Capture Text vùng barcode text → biến tracking → Type Text vào ô tra cứu<br><i>Giải thích:</i> OCR đọc text dưới barcode — không cần thư viện barcode riêng."
    ),
    "stealth_click": (
        "<b>👻 Stealth Click — Click ẩn qua PostMessage</b><br><br>"
        "<b>Ý nghĩa:</b> Gửi click trực tiếp vào message queue của cửa sổ mục tiêu "
        "bằng Win32 PostMessage. <b>Chuột vật lý KHÔNG di chuyển</b> — bạn tự do "
        "dùng máy tính trong khi macro chạy.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động click trong app ngầm</b><br>"
        "App kế toán chạy ngầm, cần click 'Duyệt' mỗi 5 phút.<br>"
        "→ Cửa sổ = <b>'App Kế Toán'</b>, X=400, Y=300<br>"
        "→ Loop ∞: <b>Stealth Click</b> → Delay 300000ms<br>"
        "<i>Giải thích:</i> App có thể bị cửa sổ khác che — vẫn hoạt động.<br><br>"
        "<b>📌 Kịch bản 2: Click trong cửa sổ minimized</b><br>"
        "Minimize app xuống taskbar → Stealth Click vẫn gửi được.<br>"
        "→ Macro click nút mà không cần hiện cửa sổ<br>"
        "<i>Giải thích:</i> PostMessage gửi trực tiếp vào HWND, không cần foreground.<br><br>"
        "<b>⚠ Hạn chế:</b><br>"
        "• Không hoạt động với DirectX/OpenGL fullscreen (game 3D)<br>"
        "• Tọa độ là client-relative (tính từ góc trên-trái cửa sổ)<br>"
        "• Một số UWP app có thể không nhận PostMessage"
    ),
    "stealth_type": (
        "<b>👻 Stealth Type — Gõ ẩn qua WM_CHAR</b><br><br>"
        "<b>Ý nghĩa:</b> Gửi từng ký tự vào cửa sổ mục tiêu qua WM_CHAR message. "
        "<b>Bàn phím vật lý KHÔNG bị chiếm</b> — bạn vẫn gõ bình thường.<br>"
        "<hr>"
        "<b>📌 Kịch bản 1: Tự động nhập dữ liệu vào Notepad ngầm</b><br>"
        "Notepad chạy ngầm, macro gõ log mỗi phút.<br>"
        "→ Cửa sổ = <b>'Notepad'</b>, Text = '{timestamp} - OK\\n'<br>"
        "<i>Giải thích:</i> Gõ vào Notepad mà không cần Activate Window.<br><br>"
        "<b>📌 Kịch bản 2: Điền form trong app ẩn</b><br>"
        "→ Stealth Click ô input (focus) → Stealth Type nội dung<br>"
        "→ Stealth Click nút Submit<br>"
        "<i>Giải thích:</i> Kết hợp Stealth Click + Type để thao tác hoàn toàn ngầm.<br><br>"
        "<b>⚠ Lưu ý:</b><br>"
        "• Key Delay = 0: gõ tức thì (nhanh nhưng một số app cần delay)<br>"
        "• Key Delay > 0: mô phỏng gõ thật, tránh bị app từ chối"
    ),
}
